//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DriverManagementWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class delivery
    {
        public int DeliveryID { get; set; }
        public string ParcelID { get; set; }
        public Nullable<int> CustomerContactNo { get; set; }
        public string CustomerName { get; set; }
        public Nullable<int> Delivery_Driver_ID { get; set; }
        public Nullable<int> Delivery_DispatchManager_ID { get; set; }
        public Nullable<System.DateTime> DeliveryDateTime { get; set; }
        public string Address { get; set; }
        public string Status { get; set; }
    
        public virtual account account { get; set; }
        public virtual account account1 { get; set; }
    }
}
